services:
  app:
    build:
      context: .
      args:
        DEV: "true"  
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "/py/bin/python manage.py wait_for_db && 
         /py/bin/python manage.py migrate && 
         /py/bin/python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=dev
      - DB_USER=devuser
      - DB_PASSWORD=sahil123
      - DEV=true     
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: sahil123
    volumes:
      - dev-db:/var/lib/postgresql/data

volumes:
  dev-db:
